### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by orhanbalci** [charliermarsh/ruff-vscode#116]
Hi there;
First of all thanks for your efforts for developing such a good tool. I am using ruff from command line but on the same code base I'm having trouble running vs-code extension. Below is the error log.  As far as I can understand server having trouble getting type hints for typing module itself. I can provide additional information if necessary.

Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
```
Server Command [RUN]: /home/orhan/.pyenv/versions/3.7.4/envs/liveapp/bin/python /home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/tool/server.py
Server Command [DEBUG]: /home/orhan/.pyenv/versions/3.7.4/envs/liveapp/bin/python /home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/tool/_debug_server.py
Traceback (most recent call last):
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/tool/server.py", line 24, in <module>
    from ruff_lsp import server
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/ruff_lsp/server.py", line 68, in <module>
    max_workers=MAX_WORKERS,
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/pygls/server.py", line 357, in __init__
    super().__init__(protocol_cls, converter_factory, loop, max_workers)
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/pygls/server.py", line 199, in __init__
    self.lsp = protocol_cls(self, converter_factory())
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/pygls/protocol.py", line 163, in default_converter
    converter = converters.get_converter()
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/lsprotocol/converters.py", line 17, in get_converter
    return _hooks.register_hooks(converter)
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/lsprotocol/_hooks.py", line 35, in register_hooks
    _resolve_forward_references()
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/lsprotocol/_hooks.py", line 30, in _resolve_forward_references
    attrs.resolve_types(value, lsp_types.ALL_TYPES_MAP, {})
  File "/home/orhan/.vscode/extensions/charliermarsh.ruff-2023.4.0-linux-x64/bundled/libs/attr/_funcs.py", line 408, in resolve_types
    hints = typing.get_type_hints(cls, globalns=globalns, localns=localns)
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 976, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 265, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 265, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 266, in _eval_type
    if ev_args == t.__args__:
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 661, in __eq__
    return frozenset(self.__args__) == frozenset(other.__args__)
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 667, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 666, in __hash__
    return hash((Union, frozenset(self.__args__)))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 667, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 480, in __hash__
    return hash((self.__forward_arg__, self.__forward_value__))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 666, in __hash__
    return hash((Union, frozenset(self.__args__)))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 667, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 480, in __hash__
    return hash((self.__forward_arg__, self.__forward_value__))
  File "/home/orhan/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 666, in __hash__
...
RecursionError: maximum recursion depth exceeded
```

**Comment by charliermarsh** [comment]
Woah, interesting! Does this happen on all files? Or specific files?

(Thanks for the kind words :))

**Comment by orhanbalci** [comment]
Further investigated the problem. It is not about which file I open. It is about interpreter I use with vscode. I'm using python 3.7.4 interpreter inside a virualenv. I can use the plugin with 3.10 interpreter which is globally installed on the machine.

**Comment by lodagro** [comment]
Same problem here, using python 3.7.1.

**Comment by charliermarsh** [comment]
I'll give this a shot with 3.7.4 today.

**Comment by charliermarsh** [comment]
FYI, it looks like `3.7.7` is the first working version.

**Comment by lodagro** [comment]
Thanks for looking into this.

**Comment by charliermarsh** [comment]
Of course. As a warning, the answer may end up being that the LSP requires >= `3.7.7`, it just depends what `pygls` decides to do.

**Comment by lodagro** [comment]
Indeed, I hope they don`t since I am stuck at 3.7.1.
I`m a long time vim user, currently evaluating vscode. Can`t imagine to do python development without ruff support.

**Comment by charliermarsh** [comment]
Closing because I _think_ this is resolved in newer versions by way of https://github.com/openlawlibrary/pygls/issues/317.)

**Comment by charliermarsh** [comment]
So, the extension _Should_ be working in older Python versions. If anyone can confirm, that'd be great.

**Comment by orhanbalci** [comment]
It is working for me now.

**Comment by lodagro** [comment]
Also working for me (python 3.7.1). Thanks!
